### ISSUE TITLE
Ссылка на источник установки нерабочая

### ISSUE THREAD

**Issue by serjevski** [DoublesunRUS/ru.capralow.dt.adaptation#1]
Ссылка http://capralow.ru/edt/unit.adaptation/latest/ не открывается, выдает что не удалось найти искомую информацию.

**Comment by DoublesunRUS** [comment]
Механизм проверок находится в процессе разработки. Нет EDT в которую плагин можно установить. Поэтому сейчас плагин в режиме разработки.
Сейчас поправлю readme.
